name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  SOLUTION_PATH: "./OweMe.Identity.sln"
  API_PROJECT_PATH: "./src/OweMe.Identity.Server"

jobs:
  build-and-test:
    name: Build, Test
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Full history for versioning

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - uses: dotnet/nbgv@master
        id: nbgv

      - name: Dotnet restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
          
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
          
      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

  push-to-ghcr:
    name: Push Docker Image to GHCR
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set lower case repository name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/OweMe.Identity.Server/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/owe-me-identity:${{ needs.build-and-test.outputs.semver }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: [build-and-test, push-to-ghcr]
    permissions:
      contents: read
    steps:
      - name: Install Render CLI
        run: curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh

      - name: Deploy and wait for result
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploys create "${{ secrets.RENDER_SERVICE_ID_IDENTITY }}" \
            --image "ghcr.io/${{ env.REPO_LOWER }}/owe-me-identity@${{ needs.build-and-test.outputs.semver }}" \
            --wait \
            --confirm \
            --output json
  
  
