name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
          
      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - uses: dotnet/nbgv@master
        id: nbgv
      
      - name: Get version
        run: echo "${{ steps.nbgv.outputs.SemVer2 }}"

      - name: SonarQube Scan
        uses: highbyte/sonarscan-dotnet@v2.5.1
        with:
          sonarProjectKey: ${{ vars.SONAR_PROJECT_KEY }}
          sonarProjectName:  ${{ vars.SONAR_PROJECT_KEY }}
          sonarOrganization: ${{ vars.SONAR_ORG }}
          dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.scanner.scanAll=false -d:sonar.qualitygate.wait=true -d:sonar.qualitygate.timeout=300 -d:sonar.exclusions="**/Pages/**,**/Migrations/**,**/wwwroot/**"
