# vars.yml — non-secret configuration. Safe to commit.

deploy_user_ssh_pubkey: ""

github_org_repo: "mrd4rkne/oweme-ecosystem"   # used to build ghcr.io/<org>/<repo>/<image>

grafana_admin_user: "admin"
grafana_hostname: "oweme-grafana.duckdns.org"
letsencrypt_email: "marcinsz.pv@gmail.com"

auth_hostname: "oweme-auth.duckdns.org"
api_hostname: "oweme-api.duckdns.org"