<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>

        <!-- Override the Directory.Build.props testing configuration -->
        <UseMicrosoftTestingPlatformRunner>false</UseMicrosoftTestingPlatformRunner>
        <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.PostgreSql"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\OweMe.Domain\OweMe.Domain.csproj"/>
    </ItemGroup>

</Project>
