<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\OweMe.Api\OweMe.Api.csproj"/>
        <ProjectReference Include="..\..\src\OweMe.Application\OweMe.Application.csproj"/>
        <ProjectReference Include="..\..\src\OweMe.Persistence\OweMe.Persistence.csproj"/>
        <ProjectReference Include="..\OweMe.Tests.Common\OweMe.Tests.Common.csproj"/>
    </ItemGroup>

</Project>
