<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Duende.IdentityModel"/>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Http"/>
        <PackageReference Include="MartinCostello.Logging.XUnit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\client\OweMe.Api.Client\OweMe.Api.Client.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="appsettings.json"/>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <None Remove="appsettings.Development.json"/>
    </ItemGroup>

</Project>
