<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="MartinCostello.Logging.XUnit.v3"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\OweMe.Api\OweMe.Api.csproj"/>
    </ItemGroup>
</Project>
