<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Testcontainers.PostgreSql"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\OweMe.Application\OweMe.Application.csproj"/>
        <ProjectReference Include="..\..\src\OweMe.Persistence\OweMe.Persistence.csproj"/>
        <ProjectReference Include="..\OweMe.Tests.Common\OweMe.Tests.Common.csproj"/>
    </ItemGroup>

</Project>
