# Override file for debugging purposes
# Use with: docker-compose -f ../compose.yaml -f compose.override.yaml up

name: oweme-system

services:
  oweme.identity:
    build:
      context: ../..
      dockerfile: src/auth/src/OweMe.Identity.Server/Dockerfile

  oweme.identity.migrator:
      build:
          context: ../..
          dockerfile: src/auth/src/OweMe.Identity.Server/Dockerfile
