<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Duende.IdentityModel" Version="7.1.0" />
    <PackageVersion Include="Duende.IdentityServer" Version="7.3.1" />
    <PackageVersion Include="Duende.IdentityServer.AspNetIdentity" Version="7.3.1" />
    <PackageVersion Include="Duende.IdentityServer.EntityFramework" Version="7.3.1" />
    <PackageVersion Include="Duende.IdentityServer.EntityFramework.Storage" Version="7.3.1" />
    <PackageVersion Include="Duende.IdentityServer.Storage" Version="7.3.1" />
    <!-- Database and ORM -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.17" />
    <PackageVersion Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="9.0.17" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.17" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <!-- Monitoring -->
    <PackageVersion Include="OpenTelemetry" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
    <!-- Versioning -->
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.7.115" />
    <!-- Command line-->
    <PackageVersion Include="System.CommandLine" Version="2.0.9" />
  </ItemGroup>
  <!-- Tests-->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="9.0.18" />
    <PackageVersion Include="Testcontainers" Version="4.6.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.6.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.9" />
    <PackageVersion Include="MartinCostello.Logging.XUnit" Version="0.7.1" />
  </ItemGroup>
</Project>