# Override file for debugging purposes
# Use with: docker-compose -f ../compose.yaml -f compose.override.yaml up

name: oweme-system
  
services:
  oweme.api:
    build:
      context: ..
      dockerfile: api/api/src/OweMe.Api/Dockerfile