name: Build nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  verify-api:
    name: Verify API
    uses: ./.github/workflows/build-api.yml
    secrets: inherit
    with:
      sonar_enforce_quality_gate: false

  verify-auth:
    name: Verify Authentication
    uses: ./.github/workflows/build-auth.yml
    secrets: inherit
    with:
      sonar_enforce_quality_gate: false
