name: PR Verification

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

permissions:
  contents: read
  checks: write

jobs:
  verify-api:
    name: Verify API
    uses: ./.github/workflows/build-api.yml
    secrets: inherit

  verify-auth:
    name: Verify Authentication
    uses: ./.github/workflows/build-auth.yml
    secrets: inherit
