name: Configure Environments

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - ".github/workflows/deploy_environments.yml"
      - "infra/**"
  pull_request:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  provision:
    uses: ./.github/workflows/provision-infra.yml
    with:
      environment_name: 'staging'
    secrets: inherit

  provision-prod:
    uses: ./.github/workflows/provision-infra.yml
    with:
      environment_name: 'production'
    secrets: inherit
