name: Publish Auth

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write

jobs:
  publish-auth:
    name: Publish Auth
    uses: ./.github/workflows/push-to-ghcr.yml
    with:
      image_name: 'oweme-auth'
      dockerfile_path: 'auth/src/OweMe.Identity.Server/Dockerfile'
      working_dir: 'auth'
      push_latest: ${{ github.ref_name == 'main' }}
