name: Publish API

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  publish-api:
    name: Publish API
    uses: ./.github/workflows/push-to-ghcr.yml
    with:
      image_name: 'oweme-api'
      dockerfile_path: 'api/api/src/OweMe.Api/Dockerfile'
      working_dir: 'api'
      push_latest: ${{ github.ref_name == 'main' }}
